spring.application.name: config-server
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shashank0271/linkedin-config-server
          default-label: main
server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
