spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shashank0271/linkedin-config-server
          default-label: main
server:
  port: 8888

