spring:
  config:
    import:
      - configserver:http://172.22.154.68:8888
  kafka:
    bootstrap-server: 172.22.154.68:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
